from pathlib import Path
p=Path('app/page.tsx');s=p.read_text()
s=s.replace("import {Checkbox} from '@/components/ui/checkbox';",'')
s=s.replace('validAnswer,type Answers,type Question','validAnswer,applicable,type Answers,type Question')
s=s.replace("'Ваше образование'","'Опыт работы и стажировок'").replace("'Образование','Профессиональное поле'","'Опыт работы','Профессиональное поле'")
a=s.index('const steps=');b=s.index('export default function Home()')
s=s[:a]+'''const baseSteps=sections.flatMap((s,si)=>{const out:{section:number;questions:Question[]}[]=[];for(let j=0;j<s.questions.length;){let n=1;if(si===9)n=s.questions.length;else if(s.questions[j].type==='likert'){while(n<3&&j+n<s.questions.length&&s.questions[j+n].group===s.questions[j].group)n++;}out.push({section:si,questions:s.questions.slice(j,j+n)});j+=n;}return out;});
const all:Question[]=sections.flatMap(s=>s.questions);
const KEY='trajectory-survey-draft-v2';
''' +s[b:]
s=s.replace(",[vkConsent,setVkConsent]=useState(false)",'')
s=s.replace("const submissionId=useRef('');", "const steps=baseSteps.filter(s=>s.questions.some(q=>applicable(q,answers)));const required=all.filter(q=>!q.optional&&applicable(q,answers));const vkConsent=answers.s10q1==='Да';const submissionId=useRef('');")
s=s.replace('localStorage.getItem(KEY)','sessionStorage.getItem(KEY)').replace('localStorage.setItem(KEY','sessionStorage.setItem(KEY').replace('localStorage.removeItem(KEY)','sessionStorage.removeItem(KEY)')
s=s.replace("try{const raw=sessionStorage.getItem(KEY);", "try{localStorage.removeItem('trajectory-survey-draft-v1');const raw=sessionStorage.getItem(KEY);")
s=s.replace("if(d.answers&&typeof d.answers==='object'&&Number.isInteger(d.step)","if(d.savedAt>Date.now()-4*60*60*1000&&d.answers&&typeof d.answers==='object'&&Number.isInteger(d.step)")
s=s.replace('setVkConsent(d.vkConsent===true);','')
s=s.replace('JSON.stringify({answers,step,vkConsent,id:submissionId.current})','JSON.stringify({answers:Object.fromEntries(Object.entries(answers).filter(([k])=>k!=="s10q2")),step,savedAt:Date.now(),id:submissionId.current})')
s=s.replace("function put(id:string,value:string){setAnswers(a=>({...a,[id]:value}));", "function put(id:string,value:string){setAnswers(a=>({...a,[id]:value,...(id==='s10q1'&&value!=='Да'?{s10q2:''}:{})}));")
s=s.replace("current.questions.find(q=>!validAnswer(q,answers[q.id]))","current.questions.find(q=>applicable(q,answers)&&!validAnswer(q,answers[q.id]))")
s=s.replace("if(answers.s10q1?.trim()&&!vkConsent){", "if(answers.s10q2?.trim()&&!vkConsent){")
s=s.replace("try{const res=await fetch('/api/responses'", "try{const session=await fetch('/api/session',{cache:'no-store'});if(!session.ok)throw new Error(session.status===429?'Слишком много запросов. Подождите 10 минут и повторите отправку.':'Не удалось установить защищённое соединение. Попробуйте ещё раз.');const {csrf}=await session.json();const res=await fetch('/api/responses'")
s=s.replace("'Content-Type':'application/json'","'Content-Type':'application/json','X-Survey-CSRF':csrf")
s=s.replace('JSON.stringify({id:submissionId.current,answers,vkConsent})','JSON.stringify({id:submissionId.current,answers:Object.fromEntries(all.filter(q=>applicable(q,answers)).map(q=>[q.id,answers[q.id]||\'\'])),vkConsent,questionnaireVersion:2})')
s=s.replace('if(!res.ok)throw new Error();','if(!res.ok)throw new Error(res.status===429?\'Слишком много отправок. Подождите 10 минут и повторите.\':\'Не удалось отправить ответы. Они остались здесь — попробуйте ещё раз.\');')
s=s.replace("}catch{setError('Не удалось отправить ответы. Они остались здесь — попробуйте ещё раз. Вы также можете скачать их.')}","}catch(e){setError(e instanceof Error?e.message:'Не удалось отправить ответы. Попробуйте ещё раз.')}")
s=s.replace('...s.questions.map(q=>{let a=', '...s.questions.filter(q=>applicable(q,answers)).map(q=>{let a=')
s=s.replace('scale(sections.indexOf(s))[Number(a)-1]',"('scale' in q?q.scale:[] as string[])[Number(a)-1]")
s=s.replace('validAnswer(q,answers[q.id])))}','(!applicable(q,answers)||validAnswer(q,answers[q.id]))))}')
s=s.replace('Черновик хранится только в этом браузере до отправки.', 'Черновик хранится в этой вкладке до её закрытия, не более 4 часов. Ссылка VK в черновик не записывается.')
s=s.replace('Данные анонимизируются на этапе обработки, не публикуются персонально и используются только в научных целях.', 'Ссылка хранится отдельно от основных ответов и дополнительно шифруется. Связь с ответами используется только для указанной исследовательской цели. Данные не публикуются персонально.')
s=s.replace("{si===3?'Оцените доступность каждой возможности.':si===5?'Оцените, насколько это важно для вас.':si===7?'Оцените степень готовности по исходной шкале анкеты.':'Оцените степень согласия с каждым утверждением.'}","{current.questions[0].instruction||'Оцените степень согласия с каждым утверждением.'}")
s=s.replace('current.questions.map(q=>','current.questions.filter(q=>applicable(q,answers)).map(q=>')
s=s.replace("q.type==='number'||q.type==='url'", "q.type==='number'||q.type==='url'||q.type==='text'")
s=s.replace("q.type==='number'?'number':'url'", "q.type==='number'?'number':q.type==='url'?'url':'text'").replace("q.type==='number'?'numeric':'url'", "q.type==='number'?'numeric':q.type==='url'?'url':'text'")
s=s.replace("placeholder={q.type==='url'?'https://vk.com/ваш_профиль':'0'}", "autoComplete=\"off\" maxLength={q.type==='text'?150:1000} placeholder={q.type==='url'?'https://vk.com/ваш_профиль':q.type==='text'?'Например, Московская область':'0'}")
s=s.replace('scale(si)[i]',"q.scale?.[i]")
s=s.replace('1 — минимальная оценка',"1 — {q.scaleEnds?.[0]||'минимальная оценка'}").replace('10 — максимальная',"10 — {q.scaleEnds?.[1]||'максимальная оценка'}")
s=s.replace("q.id==='s1q4'", "q.id==='s1q5'")
a=s.index(' {si===9&&answers.s10q1');b=s.index('\n {error&&',a);s=s[:a]+s[b:]
s=s.replace('Черновик сохраняется на устройстве','Черновик — только в этой вкладке')
s=s.replace('вы соглашаетесь участвовать в исследовании.','вы соглашаетесь участвовать в исследовании.')
p.write_text(s)
